### ISSUE TITLE
The Jar package on Maven Central is NOT bundled with precompiled fastText library for Windows, Linux and MacOSX 64bit

### ISSUE THREAD

**Issue by DavidGOrtega** [carschno/JFastText#6] opened 2019-10-09 12:14 UTC
Hi,
on maven central the package just only comes with linux libraries precompiled.

**Comment by carschno** [comment] 2019-10-21 14:25
This is a duplicate of #5

**Comment by carschno** [comment] 2019-10-21 14:28
As noted in #5, the current Jar does not include the binaries for Windows and Mac OSX, unfortunately. @DavidGOrtega can you elaborate on what you are missing for Linux exactly?

**Comment by DavidGOrtega** [comment] 2019-10-21 14:49
For linux is fine, however the Readme states... 

![image](https://user-images.githubusercontent.com/414967/67215894-8f321400-f422-11e9-9f5d-b1181c3e9723.png)

this could be a waste of time for someone expecting to have it working just using the maven package under Macos or Windows

**Comment by carschno** [comment] 2019-10-21 15:15
Thanks for clarification and you are right, this should be fixed for Windows and Mac OS. I understand that it works fine for Linux though, so I'm closing this issue as a duplicate of #5.

**Closed as completed by carschno** 2019-10-21 15:15 UTC
Labels: duplicate
